apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: licensing
      docker:
        dockerfile: k8s/Dockerfile.dev

profiles:
  - name: init
    deploy:
      kustomize:
        paths:
          - "k8s"
  - name: run-api
    deploy:
      kubectl:
        manifests:
          - k8s/dist/licensing.k8s.yaml
    portForward:
      - resourceType: Service
        resourceName: ingress-nginx-controller
        port: 443
        localPort: 8444
        namespace: licensing
  - name: create-db
    deploy:
      kubectl:
        manifests:
          - k8s/dist/postgres.k8s.yaml
    portForward:
      - resourceType: Service
        resourceName: licensing-db
        port: 5432
        localPort: 15432
        namespace: licensing
  - name: run-migration
    deploy:
      kubectl:
        manifests:
          - k8s/dist/migration.k8s.yaml
  - name: run-event-export
    deploy:
      kubectl:
        manifests:
          - k8s/dist/event-export.k8s.yaml
