apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: loc00-application-secret
    namespace: "licensing"
    envs:
      - loc00/application-secret.env
  - name: loc00-tls-secret
    namespace: "licensing"
    type: "kubernetes.io/tls"
    files:
      - loc00/tls.key
      - loc00/tls.crt
  - name: loc00-licensing-service-private-key
    namespace: "licensing"
    files:
      - LICENSING_SERVICE_PRIVATE_KEY=loc00/licensing-service.key
  - name: loc00-shop-service-private-key
    namespace: "licensing"
    files:
      - SHOP_SERVICE_PRIVATE_KEY=loc00/shop-service.key
  - name: loc00-invoice-service-auth-password
    namespace: "licensing"
    files:
      - SHOP_INVOICE_AUTH_PASSWORD=loc00/invoice-service-auth.pwd
  - name: loc00-sdwh-postgres-secret
    namespace: "licensing"
    files:
      - SDWH_POSTGRES_SECRET=loc00/sdwh-postgres-secret.pwd
  - name: loc00-sdwh-host-private-key
    namespace: "licensing"
    files:
      - SDWH_HOST_PRIVATE_KEY=loc00/sdwh-host-private.key
  - name: loc00-sdwh-private-ip
    namespace: "licensing"
    files:
      - SDWH_PRIVATE_IP=loc00/sdwh-private-ip.txt
  - name: loc00-data-event-api-secret
    namespace: "licensing"
    files:
      - SDWH_PRIVATE_IP=loc00/data-event-api-secret.txt

resources:
  - dist/ingress-nginx.k8s.yaml
  - dist/licensing-config.k8s.yaml
  - dist/licensing-service-account.k8s.yaml

patches:
  - target:
      kind: Job
      namespace: licensing
    patch: |-
      - op: add
        path: /spec/ttlSecondsAfterFinished
        value: 60
